#!/bin/sh

trap "exit" SIGINT

line=$(grep arn:aws:iam:: ~/.aws/assume-role.conf | sed -e 's/arn:aws:iam:://' | peco)
role=${line/* /}

if [ -z "$role" ]; then
  exit
fi

res=$(aws sts assume-role --role-arn arn:aws:iam::$role --role-session-name temporary)

AWS_ACCESS_KEY_ID=$(echo $res | jq -r .Credentials.AccessKeyId) \
  AWS_SECRET_ACCESS_KEY=$(echo $res | jq -r .Credentials.SecretAccessKey) \
  AWS_SESSION_TOKEN=$(echo $res | jq -r .Credentials.SessionToken) \
  exec bash
